// Regenerates MEDIA_SOURCES.md from scripts/product-image-manifest.json.
// Run after adding or replacing a photo: npm run media:record
import { existsSync, readFileSync, writeFileSync } from 'node:fs';

const manifest = JSON.parse(
  readFileSync('scripts/product-image-manifest.json', 'utf8'),
);
const seed = readFileSync('drizzle/0001_catalog.sql', 'utf8');
// Photos the catalog seed actually points at.
const listed = new Set(
  [...seed.matchAll(/'\/products\/([a-z0-9-]+)\.webp'/g)].map((m) => m[1]),
);

// Default status per source type. Change an entry in `rights` inside the
// manifest once written permission (or a manufacturer media licence) is on file.
function status(entry) {
  if (entry.rights) return entry.rights;
  const host = new URL(entry.sourcePage).hostname.replace(/^www\./, '');
  if (host === 'gccgamers.com' || host === 'store.alnabaa.com')
    return 'NOT CONFIRMED. Copied from another retailer. Replace with a manufacturer or own photo, or get written permission.';
  return 'NOT CONFIRMED. Manufacturer or distributor page. Check its media or reseller terms.';
}

const rows = manifest.map((entry) => {
  const file = `public/products/${entry.slug}.webp`;
  const notes = [
    existsSync(file) ? '' : 'file missing',
    listed.has(entry.slug) ? '' : 'no product uses this photo',
  ].filter(Boolean);
  return `| \`${entry.slug}\` | ${new URL(entry.sourcePage).hostname} ([page](${entry.sourcePage})) | ${status(entry)}${notes.length ? ` (${notes.join('; ')})` : ''} |`;
});

writeFileSync(
  'MEDIA_SOURCES.md',
  `# Media sources and usage rights

Generated by \`npm run media:record\` from \`scripts/product-image-manifest.json\`. Do not edit the table by hand.

A photo that can be found online is not automatically licensed for commercial use.
No product photo below has confirmed usage rights yet. Until each one is confirmed,
treat it as a temporary placeholder and replace it with the owner's own photo,
a manufacturer media-kit image used under its terms, or an image with written permission.

## Brand and interface assets

| File | Source | Rights |
| --- | --- | --- |
| \`public/blackshark-logo.png\` | Supplied by the store owner (BS Gaming logo) | Owner's brand asset |
| \`public/icon-32.png\`, \`public/icon-192.png\`, \`public/apple-touch-icon.png\` | Resized copies of the BS Gaming logo (browser-tab and home-screen icons) | Owner's brand asset |
| \`public/product-photo-needed.svg\` | Created for this project | Project asset |

## Product photos (${manifest.length})

Listings without a verified photo (the four generic BLACKSHARK products) use
\`product-photo-needed.svg\` until the owner uploads photos of the real items.

| Product slug | Source | Rights status |
| --- | --- | --- |
${rows.join('\n')}
`,
);
console.log(`Wrote MEDIA_SOURCES.md with ${manifest.length} product photos.`);
